apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-hostpath
spec:
  capacity:
    storage: 5Gi # Tamaño del disco
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-clase-magico # ¡Debe coincidir con el paso 1!
  hostPath:
    path: /tmp/datos-mysql-clase
    type: DirectoryOrCreate
