apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m" # El Pod pide el 20% de un núcleo de CPU
