apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: logging
spec:
 selector:
    matchLabels:
      app: logging
 template:
   metadata:
     labels:
       app: logging
   spec:
     nodeSelector:
       app: logging-node
     containers:
       - name: webserver
         image: nginx
         ports:
         - containerPort: 80


