apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: aspnetapp
        image: santospardos/sanvalero:aspnet-mssql-web
        ports:
        - containerPort: 80